# Generated by Django 4.0.6 on 2022-10-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='title_az',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(max_length=20),
        ),
    ]
