# Generated by Django 4.0.6 on 2022-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_feature_title_az_alter_feature_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='text_az',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='feature',
            name='text_en',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='feature',
            name='text_ru',
            field=models.TextField(max_length=120),
        ),
    ]
