# Generated by Django 4.0.6 on 2022-10-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_technology_name_az_remove_technology_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='technologies',
        ),
        migrations.AddField(
            model_name='skill',
            name='technologies',
            field=models.ManyToManyField(to='api.technology'),
        ),
    ]
