# Generated by Django 4.0.6 on 2022-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_name_en_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='help_text_az',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='technology',
            name='help_text_en',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='technology',
            name='help_text_ru',
            field=models.TextField(max_length=120),
        ),
    ]
