# Generated by Django 4.1.2 on 2022-10-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_navelement_social_delete_contact_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navelement',
            old_name='file_path',
            new_name='img',
        ),
    ]
