# Generated by Django 4.1.2 on 2022-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_file_path_navelement_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('welcome_text', models.CharField(max_length=40)),
                ('contactme', models.CharField(max_length=20)),
                ('msg_name', models.CharField(max_length=20)),
                ('msg_email', models.CharField(max_length=20)),
                ('msg_message', models.CharField(max_length=20)),
            ],
        ),
    ]
