# Generated by Django 4.1.2 on 2022-10-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='contactme',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='layout',
            name='welcome_text',
            field=models.CharField(max_length=100),
        ),
    ]
