# Generated by Django 4.1.2 on 2022-10-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_layout_contactme_alter_layout_welcome_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='msg_email',
        ),
    ]
