# Generated by Django 4.1.2 on 2022-10-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_layout_msg_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='', upload_to='frontend/images/'),
            preserve_default=False,
        ),
    ]
