# Generated by Django 4.1.2 on 2022-10-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_project_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='description_az',
            field=models.TextField(default='', max_length=480),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(default='', max_length=480),
            preserve_default=False,
        ),
    ]
