# Generated by Django 4.1.2 on 2022-10-31 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_description_project_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='img',
            field=models.ImageField(default='', upload_to='frontend/images/technologies/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='file_path',
            field=models.FileField(upload_to='frontend/images/features/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='navelement',
            name='img',
            field=models.FileField(upload_to='frontend/images/nav/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='frontend/images/projects/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='file_path',
            field=models.FileField(upload_to='frontend/images/social/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
