# Generated by Django 4.1.3 on 2022-11-02 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_technology_img_alter_feature_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='msg_invalid_email',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='msg_sended',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='projects_notfound',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='img',
            field=models.FileField(upload_to='frontend/images/technologies/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
