# Generated by Django 4.1.2 on 2022-11-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_social_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='all_techs',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='slected_techs',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
