# Generated by Django 4.1.2 on 2022-11-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_layout_all_techs_layout_slected_techs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='slected_techs',
            new_name='selected_techs',
        ),
    ]
