# Generated by Django 4.1.3 on 2023-06-24 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_slected_techs_layout_selected_techs'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='frontend/images/about/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('title_en', models.CharField(max_length=20)),
                ('title_ru', models.CharField(max_length=20)),
                ('title_az', models.CharField(max_length=20)),
                ('text_en', models.TextField(max_length=120)),
                ('text_ru', models.TextField(max_length=120)),
                ('text_az', models.TextField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
