# Generated by Django 4.1.3 on 2023-06-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_contactme_layout_contact_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='all_techs',
            new_name='all_technologies',
        ),
        migrations.RenameField(
            model_name='layout',
            old_name='selected_techs',
            new_name='selected_technologies',
        ),
    ]
