# Generated by Django 4.1.3 on 2023-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_all_techs_layout_all_technologies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text_az',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_en',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='about',
            name='text_ru',
            field=models.TextField(max_length=400),
        ),
    ]
