# Generated by Django 4.1.3 on 2023-06-29 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_layout_something_went_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='img',
            field=models.FileField(default='', upload_to='frontend/images/myimage/', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'png'])]),
            preserve_default=False,
        ),
    ]
