# Generated by Django 4.1.3 on 2023-06-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_layout_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='img',
        ),
    ]
