# Generated by Django 4.1.3 on 2023-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_layout_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='portfolio_page_helper',
            field=models.CharField(default='Click on the hexagon to open related projects', max_length=40),
            preserve_default=False,
        ),
    ]
