# Generated by Django 4.1.3 on 2023-07-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_layout_portfolio_page_helper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='portfolio_page_helper',
            field=models.CharField(max_length=60),
        ),
    ]
