# Generated by Django 4.1.2 on 2023-07-05 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='file_path',
            field=models.FileField(upload_to='frontend/dist/images/about/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='navelement',
            name='img',
            field=models.FileField(upload_to='frontend/dist/images/nav/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='frontend/dist/images/projects/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='file_path',
            field=models.FileField(upload_to='frontend/dist/images/social/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='img',
            field=models.FileField(upload_to='frontend/dist/images/technologies/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
